/* Generate data/marnet.cjs from the eurostat marnet_plus_100km GeoJSON.
 *
 * The network is emitted as a single CommonJS asset (JSON string + JSON.parse)
 * that both the CJS and ESM builds resolve at runtime, instead of being inlined
 * into each build's marnet module. Shipping it once (as dist/data/marnet.cjs)
 * roughly halves the published package size.
 *
 * Run manually when refreshing the network:
 *   node scripts/build-marnet.cjs /path/to/marnet_plus_100km.geojson
 */
const fs = require('fs');
const path = require('path');

const input = process.argv[2] || '/tmp/eurostat-marnet/marnet_plus_100km.geojson';
const outPath = path.resolve(__dirname, '..', 'data/marnet.cjs');

const src = fs.readFileSync(input, 'utf8');
const parsed = JSON.parse(src);

// Antimeridian normalization: collapse lon=180 onto lon=-180 so the eastern
// and western Pacific share a single graph vertex.
let touched = 0;
for (const f of parsed.features) {
  for (const c of f.geometry.coordinates) {
    if (c[0] === 180) {
      c[0] = -180;
      touched++;
    }
  }
}

const json = JSON.stringify(parsed);
if (json.includes("'") || json.includes('\\')) {
  console.error('JSON contains characters that need escaping in a JS single-quoted string');
  process.exit(1);
}

const header = `/* Auto-generated by scripts/build-marnet.cjs. Do not edit by hand.
 *
 * Single shared copy of the Eurostat marnet_plus_100km network, loaded by
 * both the CJS and ESM builds (see src/lib/marnet.ts). Shipping the network
 * as one asset instead of inlining it into each build roughly halves the
 * published package size.
 *
 * Source: https://github.com/eurostat/searoute (EUPL-1.2).
 */
`;

const body = 'module.exports = JSON.parse(\n  \'' + json + '\',\n);\n';

fs.writeFileSync(outPath, header + body);
console.log('normalized', touched, 'antimeridian vertices');
console.log('wrote', outPath, '(' + (fs.statSync(outPath).size / 1024 / 1024).toFixed(2) + ' MB)');
