/* Generate src/ports/data.ts from the marchah/sea-ports dataset.
 *
 * Source: https://github.com/marchah/sea-ports (MIT), a curated set of seaports
 * keyed by UN/LOCODE with coordinates, itself derived from UN/LOCODE. We keep
 * only { name, country, coordinates } and index every UN/LOCODE alias so both a
 * port's primary code and its aliases resolve.
 *
 * The data is embedded as a JSON string + JSON.parse() so the TypeScript
 * compiler doesn't pretty-print a large object literal. Ships behind the
 * `searoute-ts/ports` subpath export so the core stays lean.
 *
 * Refresh with:
 *   curl -sSL https://raw.githubusercontent.com/marchah/sea-ports/master/lib/ports.json -o /tmp/seaports.json
 *   node scripts/build-ports.cjs /tmp/seaports.json
 */
const fs = require('fs');
const path = require('path');

const input = process.argv[2] || '/tmp/seaports.json';
const outPath = path.resolve(__dirname, '..', 'src/ports/data.ts');

const source = JSON.parse(fs.readFileSync(input, 'utf8'));

const isValidCode = (code) => /^[A-Z]{2}[A-Z0-9]{3}$/.test(code);
const isValidCoord = (c) =>
  Array.isArray(c) &&
  c.length === 2 &&
  Number.isFinite(c[0]) &&
  Number.isFinite(c[1]) &&
  Math.abs(c[0]) <= 180 &&
  Math.abs(c[1]) <= 90;

const round = (n) => Math.round(n * 1e6) / 1e6;

const ports = {};
let skipped = 0;
for (const [key, entry] of Object.entries(source)) {
  const coords = entry.coordinates;
  if (!isValidCoord(coords)) {
    skipped++;
    continue;
  }
  const record = {
    name: entry.name,
    country: entry.country || '',
    coordinates: [round(coords[0]), round(coords[1])],
  };
  const codes = new Set([key, ...(Array.isArray(entry.unlocs) ? entry.unlocs : [])]);
  for (const raw of codes) {
    const code = String(raw).toUpperCase();
    if (!isValidCode(code)) continue;
    if (!ports[code]) ports[code] = record; // first entry wins on collisions
  }
}

// Deterministic key order keeps the generated file stable across runs.
const sorted = {};
for (const code of Object.keys(ports).sort()) sorted[code] = ports[code];

const json = JSON.stringify(sorted);
const literal = JSON.stringify(json); // safe double-quoted JS string literal

const header = `/* Auto-generated by scripts/build-ports.cjs. Do not edit by hand.
 *
 * Curated seaport dataset keyed by UN/LOCODE, derived from
 * https://github.com/marchah/sea-ports (MIT), itself based on UN/LOCODE.
 * Only { name, country, coordinates: [lon, lat] } is kept, indexed by every
 * UN/LOCODE alias. Embedded as a JSON string parsed once at module load.
 */
export type PortRecord = { name: string; country: string; coordinates: [number, number] };

const PORTS: Record<string, PortRecord> = JSON.parse(${literal}) as Record<string, PortRecord>;

export default PORTS;
`;

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, header);
console.log(
  'wrote',
  path.relative(path.resolve(__dirname, '..'), outPath),
  '—',
  Object.keys(sorted).length,
  'codes,',
  skipped,
  'entries skipped (no coords),',
  (fs.statSync(outPath).size / 1024).toFixed(0),
  'KB',
);
