/* Generate a shared network asset (data/marnet[-<resolution>].cjs) from a
 * Eurostat marnet_plus GeoJSON.
 *
 * The network is emitted as a single CommonJS asset (JSON string + JSON.parse)
 * that both the CJS and ESM builds resolve at runtime, instead of being inlined
 * into each build's marnet module. Shipping it once (as dist/data/…) roughly
 * halves the published package size (issue #10).
 *
 * Eurostat ships the network at 5 / 10 / 20 / 50 / 100 km resolutions as
 * GeoPackage files in eurostat/searoute
 * (modules/core/src/main/resources/marnet/marnet_plus_<res>.gpkg). Convert the
 * one you want to GeoJSON (WGS84, 6-decimal precision) first, e.g. with GDAL:
 *
 *   ogr2ogr -f GeoJSON -lco COORDINATE_PRECISION=6 \
 *     marnet_plus_20km.geojson marnet_plus_20km.gpkg
 *
 * then run this script with an optional resolution label. Without a label the
 * output is the bundled default (data/marnet.cjs, 100 km); with one it is a
 * resolution variant exposed as a subpath export (issue #11):
 *
 *   node scripts/build-marnet.cjs marnet_plus_100km.geojson          # -> data/marnet.cjs
 *   node scripts/build-marnet.cjs marnet_plus_20km.geojson 20km      # -> data/marnet-20km.cjs
 *   node scripts/build-marnet.cjs marnet_plus_50km.geojson 50km      # -> data/marnet-50km.cjs
 *
 * A companion .d.cts type declaration is (re)generated alongside each asset.
 */
const fs = require('fs');
const path = require('path');

const input = process.argv[2] || '/tmp/eurostat-marnet/marnet_plus_100km.geojson';
const resolution = process.argv[3]; // e.g. '20km'; omit for the default 100 km network

const dataDir = path.resolve(__dirname, '..', 'data');
const baseName = resolution ? `marnet-${resolution}` : 'marnet';
const outPath = path.join(dataDir, `${baseName}.cjs`);
const dtsPath = path.join(dataDir, `${baseName}.d.cts`);

const src = fs.readFileSync(input, 'utf8');
const parsed = JSON.parse(src);

// Antimeridian normalization: collapse lon=180 onto lon=-180 so the eastern
// and western Pacific share a single graph vertex.
let touched = 0;
for (const f of parsed.features) {
  const geoms =
    f.geometry.type === 'MultiLineString' ? f.geometry.coordinates : [f.geometry.coordinates];
  for (const line of geoms) {
    for (const c of line) {
      if (c[0] === 180) {
        c[0] = -180;
        touched++;
      }
    }
  }
}

const json = JSON.stringify(parsed);
if (json.includes("'") || json.includes('\\')) {
  console.error('JSON contains characters that need escaping in a JS single-quoted string');
  process.exit(1);
}

const label = resolution ? `marnet_plus_${resolution}` : 'marnet_plus_100km';
const header = `/* Auto-generated by scripts/build-marnet.cjs. Do not edit by hand.
 *
 * Single shared copy of the Eurostat ${label} network, loaded by both the CJS
 * and ESM builds (see src/lib/marnet.ts / src/marnet/*.ts). Shipping the
 * network as one asset instead of inlining it into each build roughly halves
 * the published package size.
 *
 * Source: https://github.com/eurostat/searoute (EUPL-1.2).
 */
`;

const body = 'module.exports = JSON.parse(\n  \'' + json + '\',\n);\n';

fs.writeFileSync(outPath, header + body);

const dts = `import type { FeatureCollection, LineString } from 'geojson';

/** Optional native passage label carried on marnet edges. */
export type MarnetProperties = { pass?: string };

declare const marnetData: FeatureCollection<LineString, MarnetProperties>;
export default marnetData;
`;
fs.writeFileSync(dtsPath, dts);

console.log('normalized', touched, 'antimeridian vertices');
console.log('wrote', outPath, '(' + (fs.statSync(outPath).size / 1024 / 1024).toFixed(2) + ' MB)');
console.log('wrote', path.relative(path.resolve(__dirname, '..'), dtsPath));
